FROM python:3.11.7-slim

WORKDIR /usr/src/app

COPY . /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

ENV NAME World

COPY entrypoint.sh /usr/src/app/entrypoint.sh

RUN chmod +x /usr/src/app/entrypoint.sh

ENTRYPOINT ["/usr/src/app/entrypoint.sh"]

# terminal mode
CMD ["python", "./three/testing.py"]

# # ui mode
# CMD ["python", "./three/testing.py", "ui"]