FROM python:3.10

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    libopenblas-dev \
    liblapack-dev \
    libxslt-dev \
    libxml2-dev \
    libffi-dev \
    zlib1g-dev \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    torch torchvision torchaudio \
    tensorflow \
    sklearn \
    xgboost \
    matplotlib \
    seaborn \
    pandas \
    mlflow \ 
    openai \
    marqo \ 
    numpy

CMD ["python", "script_runner.py"]
